# Generated by Django 5.1.7 on 2026-06-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0002_alter_user_email"),
        ("users", "0002_user_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_assignments",
                        to="core.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_assignments",
                        to="core.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-assigned_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "patient"),
                        name="unique_doctor_patient_assignment",
                    )
                ],
            },
        ),
    ]
