# Generated by Django 6.0.6 on 2026-06-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('radiology', 'Radiology'), ('blood_test', 'Blood test'), ('physical_exam', 'Physical exam'), ('doctor_diagnosis', 'Doctor diagnosis'), ('user_note', 'User note'), ('other', 'Other')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='diagnoses/')),
                ('happened_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('extracted_findings', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('body_areas', models.JSONField(blank=True, default=list)),
                ('embedding_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='medical.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('body_area', models.CharField(blank=True, max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('embedding_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisProblemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong')], default='moderate', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='medical.diagnosis')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_links', to='medical.problem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diagnosis', 'problem'), name='unique_diagnosis_problem_link')],
            },
        ),
    ]
