# Generated by Django 6.0.6 on 2026-06-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('his_document_id', models.CharField(max_length=64, unique=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=128)),
                ('diagnosis_code', models.CharField(max_length=32)),
                ('diagnosis', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nhif_number', models.CharField(max_length=32, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Epicrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('his_document_id', models.CharField(max_length=64, unique=True)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('hospitalization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epicrisis', to='core.hospitalization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='medical_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicalinstitution'),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uin', models.CharField(max_length=32, unique=True)),
                ('specialty', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.medicalinstitution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_identifier', models.CharField(max_length=32, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('blood_type', models.CharField(blank=True, max_length=8)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('his_document_id', models.CharField(max_length=64, unique=True)),
                ('vaccine_name', models.CharField(max_length=128)),
                ('lot_number', models.CharField(max_length=64)),
                ('dose_number', models.PositiveSmallIntegerField()),
                ('immunization_date', models.DateField()),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicalinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='core.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='core.patientprofile'),
        ),
    ]
