# Generated by Django 6.0.6 on 2026-06-07 10:57

import apps.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laboratory_request', models.CharField(max_length=128)),
                ('laboratory_name', models.CharField(max_length=255)),
                ('collected_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=16)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResultAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=apps.core.storage.PrivateMediaStorage(), upload_to='laboratory_results/attachments/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('dicom', 'DICOM'), ('other', 'Other')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.laboratoryresult')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_result_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
