# Generated by Django 6.0.6 on 2026-06-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_results', to='core.patientprofile'),
        ),
    ]
