# Generated by Django 6.0.6 on 2026-06-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_emailnotification"),
        ("core", "0003_laboratoryresult_patient"),
    ]

    operations = []
